server:
  port: 7000

spring:
  profiles:
    active: dev
  application:
    name: swda-bms
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# Actuator 配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

swda:
  xss:
    enabled: true
  token:
    # 2小时过期
    access-token-expire: 7200
    # 14天过期
    refresh-token-expire: 1209600
  log:
    path: logs
  uniques:
    # system - dict type
    bms.system.dict_type.dict_type.add: select count(*) from bms_dict_type where dict_type=?
    bms.system.dict_type.dict_type.update: select count(*) from bms_dict_type where dict_type=? and dict_type_id<>?
    # system - dict
    bms.system.dict.dict_value.add: select count(*) from bms_dict where dict_value=? and dict_type=?
    bms.system.dict.dict_value.update: select count(*) from bms_dict where dict+valid=? and dict_type=? and dict_id<>?
    # system - region
    bms.system.region.region_id.add: select count(*) from bms_region where region_id=?
    bms.system.region.region_id.update: select count(*) from bms_region where region_id=? and region_id<>?
    # system - town
    bms.system.town.town_id.add: select count(*) from bms_town where town_id=?
    bms.system.town.town_id.update: select count(*) from bms_town where town_id=? and town_id<>?
    # system - system
    bms.system.system.system_code.add: select count(*) from bms_system where system_code=?
    bms.system.system.system_code.update: select count(*) from bms_system where system_code=? and system_id<>?
    # system - menu
    bms.system.menu.menu_id.add: select count(*) from bms_menu where menu_id=?
    bms.system.menu.menu_code.add: select count(*) from bms_menu where menu_code=?
    bms.system.menu.menu_code.update: select count(*) from bms_menu where menu_code=? and menu_id<>?
    # system - task
    bms.system.task.task_code.add: select count(*) from bms_task where task_code=?
    bms.system.task.task_code.update: select count(*) from bms_task where task_code=? and task_id<>?
    # permission - user
    bms.permission.user.username.add: select count(*) from bms_user where username=?
    bms.permission.user.username.update: select count(*) from bms_user where username=? and user_id<>?
    bms.permission.user.mobile.add: select count(*) from bms_user where mobile=?
    bms.permission.user.mobile.update: select count(*) from bms_user where mobile=? and user_id<>?
    # permission - organ
    bms.permission.organ.organ_code.add: select count(*) from bms_organ where organ_code=?
    bms.permission.organ.organ_code.update: select count(*) from bms_organ where organ_code=? and organ_id<>?
    # permission - post
    bms.permission.post.post_code.add: select count(*) from bms_post where post_code=?
    bms.permission.post.post_code.update: select count(*) from bms_post where post_code=? and post_id<>?
    # permission - role
    bms.permission.role.role_code.add: select count(*) from bms_role where role_code=?
    bms.permission.role.role_code.update: select count(*) from bms_role where role_code=? and role_id<>?

#easy trans 数据翻译组件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true    
  
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dlshouwen.swda.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: "null"
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

storage:
  enabled: true
  config:
    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
    type: local
    domain: http://localhost:7000
  local:
    path: D:/Temp/upload